try {
  console.log(a + b);
} catch (error) {
  console.log(error);
} finally {
  console.log("Finally");
}
